export const MOCK_DATA_RESPONSE = {
	"tracks": {
		"href": "https://api.spotify.com/v1/search?query=juice+wrld&type=track&offset=0&limit=7",
		"items": [
			{
				"album": {
					"album_type": "album",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
							},
							"href": "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
							"id": "4MCBfE4596Uoi2O4DtmEMz",
							"name": "Juice WRLD",
							"type": "artist",
							"uri": "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AG",
						"AL",
						"AM",
						"AO",
						"AR",
						"AT",
						"AU",
						"AZ",
						"BA",
						"BB",
						"BD",
						"BE",
						"BG",
						"BH",
						"BI",
						"BJ",
						"BO",
						"BR",
						"BS",
						"BT",
						"BW",
						"BY",
						"BZ",
						"CA",
						"CD",
						"CG",
						"CH",
						"CI",
						"CL",
						"CM",
						"CO",
						"CR",
						"CV",
						"CW",
						"CY",
						"CZ",
						"DE",
						"DJ",
						"DK",
						"DM",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FJ",
						"FM",
						"FR",
						"GA",
						"GB",
						"GD",
						"GE",
						"GH",
						"GM",
						"GN",
						"GQ",
						"GR",
						"GT",
						"GW",
						"GY",
						"HK",
						"HN",
						"HR",
						"HT",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IQ",
						"IS",
						"IT",
						"JM",
						"JO",
						"JP",
						"KE",
						"KG",
						"KH",
						"KI",
						"KM",
						"KN",
						"KR",
						"KW",
						"KZ",
						"LA",
						"LB",
						"LC",
						"LI",
						"LK",
						"LR",
						"LS",
						"LT",
						"LU",
						"LV",
						"LY",
						"MA",
						"MC",
						"MD",
						"ME",
						"MG",
						"MH",
						"MK",
						"ML",
						"MN",
						"MO",
						"MR",
						"MT",
						"MU",
						"MV",
						"MW",
						"MX",
						"MY",
						"MZ",
						"NA",
						"NE",
						"NG",
						"NI",
						"NL",
						"NO",
						"NP",
						"NR",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PG",
						"PH",
						"PK",
						"PL",
						"PS",
						"PT",
						"PW",
						"PY",
						"QA",
						"RO",
						"RS",
						"RU",
						"RW",
						"SA",
						"SB",
						"SC",
						"SE",
						"SG",
						"SI",
						"SK",
						"SL",
						"SM",
						"SN",
						"SR",
						"ST",
						"SV",
						"SZ",
						"TD",
						"TG",
						"TH",
						"TJ",
						"TL",
						"TN",
						"TO",
						"TR",
						"TT",
						"TV",
						"TW",
						"TZ",
						"UA",
						"UG",
						"US",
						"UY",
						"UZ",
						"VC",
						"VE",
						"VN",
						"VU",
						"WS",
						"XK",
						"ZA",
						"ZM",
						"ZW"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/6tkjU4Umpo79wwkgPMV3nZ"
					},
					"href": "https://api.spotify.com/v1/albums/6tkjU4Umpo79wwkgPMV3nZ",
					"id": "6tkjU4Umpo79wwkgPMV3nZ",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273f7db43292a6a99b21b51d5b4",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02f7db43292a6a99b21b51d5b4",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851f7db43292a6a99b21b51d5b4",
							"width": 64
						}
					],
					"name": "Goodbye & Good Riddance",
					"release_date": "2018-12-10",
					"release_date_precision": "day",
					"total_tracks": 17,
					"type": "album",
					"uri": "spotify:album:6tkjU4Umpo79wwkgPMV3nZ"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
						},
						"href": "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
						"id": "4MCBfE4596Uoi2O4DtmEMz",
						"name": "Juice WRLD",
						"type": "artist",
						"uri": "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AG",
					"AL",
					"AM",
					"AO",
					"AR",
					"AT",
					"AU",
					"AZ",
					"BA",
					"BB",
					"BD",
					"BE",
					"BG",
					"BH",
					"BI",
					"BJ",
					"BO",
					"BR",
					"BS",
					"BT",
					"BW",
					"BY",
					"BZ",
					"CA",
					"CD",
					"CG",
					"CH",
					"CI",
					"CL",
					"CM",
					"CO",
					"CR",
					"CV",
					"CW",
					"CY",
					"CZ",
					"DE",
					"DJ",
					"DK",
					"DM",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FJ",
					"FM",
					"FR",
					"GA",
					"GB",
					"GD",
					"GE",
					"GH",
					"GM",
					"GN",
					"GQ",
					"GR",
					"GT",
					"GW",
					"GY",
					"HK",
					"HN",
					"HR",
					"HT",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IQ",
					"IS",
					"IT",
					"JM",
					"JO",
					"JP",
					"KE",
					"KG",
					"KH",
					"KI",
					"KM",
					"KN",
					"KR",
					"KW",
					"KZ",
					"LA",
					"LB",
					"LC",
					"LI",
					"LK",
					"LR",
					"LS",
					"LT",
					"LU",
					"LV",
					"LY",
					"MA",
					"MC",
					"MD",
					"ME",
					"MG",
					"MH",
					"MK",
					"ML",
					"MN",
					"MO",
					"MR",
					"MT",
					"MU",
					"MV",
					"MW",
					"MX",
					"MY",
					"MZ",
					"NA",
					"NE",
					"NG",
					"NI",
					"NL",
					"NO",
					"NP",
					"NR",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PG",
					"PH",
					"PK",
					"PL",
					"PS",
					"PT",
					"PW",
					"PY",
					"QA",
					"RO",
					"RS",
					"RU",
					"RW",
					"SA",
					"SB",
					"SC",
					"SE",
					"SG",
					"SI",
					"SK",
					"SL",
					"SM",
					"SN",
					"SR",
					"ST",
					"SV",
					"SZ",
					"TD",
					"TG",
					"TH",
					"TJ",
					"TL",
					"TN",
					"TO",
					"TR",
					"TT",
					"TV",
					"TW",
					"TZ",
					"UA",
					"UG",
					"US",
					"UY",
					"UZ",
					"VC",
					"VE",
					"VN",
					"VU",
					"WS",
					"XK",
					"ZA",
					"ZM",
					"ZW"
				],
				"disc_number": 1,
				"duration_ms": 165819,
				"explicit": true,
				"external_ids": {
					"isrc": "USUG11800651"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/4VXIryQMWpIdGgYR4TrjT1"
				},
				"href": "https://api.spotify.com/v1/tracks/4VXIryQMWpIdGgYR4TrjT1",
				"id": "4VXIryQMWpIdGgYR4TrjT1",
				"is_local": false,
				"name": "All Girls Are The Same",
				"popularity": 86,
				"preview_url": null,
				"track_number": 2,
				"type": "track",
				"uri": "spotify:track:4VXIryQMWpIdGgYR4TrjT1"
			},
			{
				"album": {
					"album_type": "album",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR"
							},
							"href": "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
							"id": "7dGJo4pcD2V6oG8kP0tJRR",
							"name": "Eminem",
							"type": "artist",
							"uri": "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AG",
						"AL",
						"AM",
						"AO",
						"AR",
						"AT",
						"AU",
						"AZ",
						"BA",
						"BB",
						"BD",
						"BE",
						"BG",
						"BH",
						"BI",
						"BJ",
						"BO",
						"BR",
						"BS",
						"BT",
						"BW",
						"BZ",
						"CA",
						"CD",
						"CG",
						"CH",
						"CI",
						"CL",
						"CM",
						"CO",
						"CR",
						"CV",
						"CW",
						"CY",
						"CZ",
						"DE",
						"DJ",
						"DK",
						"DM",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FJ",
						"FM",
						"FR",
						"GA",
						"GB",
						"GD",
						"GE",
						"GH",
						"GM",
						"GN",
						"GQ",
						"GR",
						"GT",
						"GW",
						"GY",
						"HK",
						"HN",
						"HR",
						"HT",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IQ",
						"IS",
						"IT",
						"JM",
						"JO",
						"JP",
						"KE",
						"KG",
						"KH",
						"KI",
						"KM",
						"KN",
						"KR",
						"KW",
						"KZ",
						"LA",
						"LB",
						"LC",
						"LI",
						"LK",
						"LR",
						"LS",
						"LT",
						"LU",
						"LV",
						"LY",
						"MA",
						"MC",
						"MD",
						"ME",
						"MG",
						"MH",
						"MK",
						"ML",
						"MN",
						"MO",
						"MR",
						"MT",
						"MU",
						"MV",
						"MW",
						"MX",
						"MY",
						"MZ",
						"NA",
						"NE",
						"NG",
						"NI",
						"NL",
						"NO",
						"NR",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PG",
						"PH",
						"PK",
						"PL",
						"PS",
						"PT",
						"PW",
						"PY",
						"QA",
						"RO",
						"RS",
						"RU",
						"RW",
						"SA",
						"SB",
						"SC",
						"SE",
						"SG",
						"SI",
						"SK",
						"SL",
						"SM",
						"SN",
						"SR",
						"ST",
						"SV",
						"SZ",
						"TD",
						"TG",
						"TH",
						"TJ",
						"TL",
						"TN",
						"TO",
						"TR",
						"TT",
						"TV",
						"TW",
						"TZ",
						"UA",
						"UG",
						"US",
						"UY",
						"VC",
						"VE",
						"VN",
						"VU",
						"WS",
						"XK",
						"ZA",
						"ZM",
						"ZW"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/4otkd9As6YaxxEkIjXPiZ6"
					},
					"href": "https://api.spotify.com/v1/albums/4otkd9As6YaxxEkIjXPiZ6",
					"id": "4otkd9As6YaxxEkIjXPiZ6",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b2732f44aec83b20e40f3baef73c",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e022f44aec83b20e40f3baef73c",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d000048512f44aec83b20e40f3baef73c",
							"width": 64
						}
					],
					"name": "Music To Be Murdered By",
					"release_date": "2020-01-17",
					"release_date_precision": "day",
					"total_tracks": 20,
					"type": "album",
					"uri": "spotify:album:4otkd9As6YaxxEkIjXPiZ6"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR"
						},
						"href": "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
						"id": "7dGJo4pcD2V6oG8kP0tJRR",
						"name": "Eminem",
						"type": "artist",
						"uri": "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR"
					},
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
						},
						"href": "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
						"id": "4MCBfE4596Uoi2O4DtmEMz",
						"name": "Juice WRLD",
						"type": "artist",
						"uri": "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AG",
					"AL",
					"AM",
					"AO",
					"AR",
					"AT",
					"AU",
					"AZ",
					"BA",
					"BB",
					"BD",
					"BE",
					"BG",
					"BH",
					"BI",
					"BJ",
					"BO",
					"BR",
					"BS",
					"BT",
					"BW",
					"BZ",
					"CA",
					"CD",
					"CG",
					"CH",
					"CI",
					"CL",
					"CM",
					"CO",
					"CR",
					"CV",
					"CW",
					"CY",
					"CZ",
					"DE",
					"DJ",
					"DK",
					"DM",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FJ",
					"FM",
					"FR",
					"GA",
					"GB",
					"GD",
					"GE",
					"GH",
					"GM",
					"GN",
					"GQ",
					"GR",
					"GT",
					"GW",
					"GY",
					"HK",
					"HN",
					"HR",
					"HT",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IQ",
					"IS",
					"IT",
					"JM",
					"JO",
					"JP",
					"KE",
					"KG",
					"KH",
					"KI",
					"KM",
					"KN",
					"KR",
					"KW",
					"KZ",
					"LA",
					"LB",
					"LC",
					"LI",
					"LK",
					"LR",
					"LS",
					"LT",
					"LU",
					"LV",
					"LY",
					"MA",
					"MC",
					"MD",
					"ME",
					"MG",
					"MH",
					"MK",
					"ML",
					"MN",
					"MO",
					"MR",
					"MT",
					"MU",
					"MV",
					"MW",
					"MX",
					"MY",
					"MZ",
					"NA",
					"NE",
					"NG",
					"NI",
					"NL",
					"NO",
					"NR",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PG",
					"PH",
					"PK",
					"PL",
					"PS",
					"PT",
					"PW",
					"PY",
					"QA",
					"RO",
					"RS",
					"RU",
					"RW",
					"SA",
					"SB",
					"SC",
					"SE",
					"SG",
					"SI",
					"SK",
					"SL",
					"SM",
					"SN",
					"SR",
					"ST",
					"SV",
					"SZ",
					"TD",
					"TG",
					"TH",
					"TJ",
					"TL",
					"TN",
					"TO",
					"TR",
					"TT",
					"TV",
					"TW",
					"TZ",
					"UA",
					"UG",
					"US",
					"UY",
					"VC",
					"VE",
					"VN",
					"VU",
					"WS",
					"XK",
					"ZA",
					"ZM",
					"ZW"
				],
				"disc_number": 1,
				"duration_ms": 210800,
				"explicit": true,
				"external_ids": {
					"isrc": "USUM72000788"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/7FIWs0pqAYbP91WWM0vlTQ"
				},
				"href": "https://api.spotify.com/v1/tracks/7FIWs0pqAYbP91WWM0vlTQ",
				"id": "7FIWs0pqAYbP91WWM0vlTQ",
				"is_local": false,
				"name": "Godzilla (feat. Juice WRLD)",
				"popularity": 86,
				"preview_url": null,
				"track_number": 7,
				"type": "track",
				"uri": "spotify:track:7FIWs0pqAYbP91WWM0vlTQ"
			},
			{
				"album": {
					"album_type": "album",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
							},
							"href": "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
							"id": "4MCBfE4596Uoi2O4DtmEMz",
							"name": "Juice WRLD",
							"type": "artist",
							"uri": "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AG",
						"AL",
						"AM",
						"AO",
						"AR",
						"AT",
						"AU",
						"AZ",
						"BA",
						"BB",
						"BD",
						"BE",
						"BF",
						"BG",
						"BH",
						"BI",
						"BJ",
						"BN",
						"BO",
						"BR",
						"BS",
						"BT",
						"BW",
						"BY",
						"BZ",
						"CA",
						"CD",
						"CG",
						"CH",
						"CI",
						"CL",
						"CM",
						"CO",
						"CR",
						"CV",
						"CW",
						"CY",
						"CZ",
						"DE",
						"DJ",
						"DK",
						"DM",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FJ",
						"FM",
						"FR",
						"GA",
						"GB",
						"GD",
						"GE",
						"GH",
						"GM",
						"GN",
						"GQ",
						"GR",
						"GT",
						"GW",
						"GY",
						"HK",
						"HN",
						"HR",
						"HT",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IQ",
						"IS",
						"IT",
						"JM",
						"JO",
						"JP",
						"KE",
						"KG",
						"KH",
						"KI",
						"KM",
						"KN",
						"KR",
						"KW",
						"KZ",
						"LA",
						"LB",
						"LC",
						"LI",
						"LK",
						"LR",
						"LS",
						"LT",
						"LU",
						"LV",
						"LY",
						"MA",
						"MC",
						"MD",
						"ME",
						"MG",
						"MH",
						"MK",
						"ML",
						"MN",
						"MO",
						"MR",
						"MT",
						"MU",
						"MV",
						"MW",
						"MX",
						"MY",
						"MZ",
						"NA",
						"NE",
						"NG",
						"NI",
						"NL",
						"NO",
						"NP",
						"NR",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PG",
						"PH",
						"PK",
						"PL",
						"PS",
						"PT",
						"PW",
						"PY",
						"QA",
						"RO",
						"RS",
						"RU",
						"RW",
						"SA",
						"SB",
						"SC",
						"SE",
						"SG",
						"SI",
						"SK",
						"SL",
						"SM",
						"SN",
						"SR",
						"ST",
						"SV",
						"SZ",
						"TD",
						"TG",
						"TH",
						"TJ",
						"TL",
						"TN",
						"TO",
						"TR",
						"TT",
						"TV",
						"TW",
						"TZ",
						"UA",
						"UG",
						"US",
						"UY",
						"UZ",
						"VC",
						"VE",
						"VN",
						"VU",
						"WS",
						"XK",
						"ZA",
						"ZM",
						"ZW"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/6n9DKpOxwifT5hOXtgLZSL"
					},
					"href": "https://api.spotify.com/v1/albums/6n9DKpOxwifT5hOXtgLZSL",
					"id": "6n9DKpOxwifT5hOXtgLZSL",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b2733e0698e4ae5ffb82a005aeeb",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e023e0698e4ae5ffb82a005aeeb",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d000048513e0698e4ae5ffb82a005aeeb",
							"width": 64
						}
					],
					"name": "Legends Never Die",
					"release_date": "2020-07-10",
					"release_date_precision": "day",
					"total_tracks": 22,
					"type": "album",
					"uri": "spotify:album:6n9DKpOxwifT5hOXtgLZSL"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
						},
						"href": "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
						"id": "4MCBfE4596Uoi2O4DtmEMz",
						"name": "Juice WRLD",
						"type": "artist",
						"uri": "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AG",
					"AL",
					"AM",
					"AO",
					"AR",
					"AT",
					"AU",
					"AZ",
					"BA",
					"BB",
					"BD",
					"BE",
					"BF",
					"BG",
					"BH",
					"BI",
					"BJ",
					"BN",
					"BO",
					"BR",
					"BS",
					"BT",
					"BW",
					"BY",
					"BZ",
					"CA",
					"CD",
					"CG",
					"CH",
					"CI",
					"CL",
					"CM",
					"CO",
					"CR",
					"CV",
					"CW",
					"CY",
					"CZ",
					"DE",
					"DJ",
					"DK",
					"DM",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FJ",
					"FM",
					"FR",
					"GA",
					"GB",
					"GD",
					"GE",
					"GH",
					"GM",
					"GN",
					"GQ",
					"GR",
					"GT",
					"GW",
					"GY",
					"HK",
					"HN",
					"HR",
					"HT",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IQ",
					"IS",
					"IT",
					"JM",
					"JO",
					"JP",
					"KE",
					"KG",
					"KH",
					"KI",
					"KM",
					"KN",
					"KR",
					"KW",
					"KZ",
					"LA",
					"LB",
					"LC",
					"LI",
					"LK",
					"LR",
					"LS",
					"LT",
					"LU",
					"LV",
					"LY",
					"MA",
					"MC",
					"MD",
					"ME",
					"MG",
					"MH",
					"MK",
					"ML",
					"MN",
					"MO",
					"MR",
					"MT",
					"MU",
					"MV",
					"MW",
					"MX",
					"MY",
					"MZ",
					"NA",
					"NE",
					"NG",
					"NI",
					"NL",
					"NO",
					"NP",
					"NR",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PG",
					"PH",
					"PK",
					"PL",
					"PS",
					"PT",
					"PW",
					"PY",
					"QA",
					"RO",
					"RS",
					"RU",
					"RW",
					"SA",
					"SB",
					"SC",
					"SE",
					"SG",
					"SI",
					"SK",
					"SL",
					"SM",
					"SN",
					"SR",
					"ST",
					"SV",
					"SZ",
					"TD",
					"TG",
					"TH",
					"TJ",
					"TL",
					"TN",
					"TO",
					"TR",
					"TT",
					"TV",
					"TW",
					"TZ",
					"UA",
					"UG",
					"US",
					"UY",
					"UZ",
					"VC",
					"VE",
					"VN",
					"VU",
					"WS",
					"XK",
					"ZA",
					"ZM",
					"ZW"
				],
				"disc_number": 1,
				"duration_ms": 194621,
				"explicit": true,
				"external_ids": {
					"isrc": "USUG12001905"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/2U5WueTLIK5WJLD7mvDODv"
				},
				"href": "https://api.spotify.com/v1/tracks/2U5WueTLIK5WJLD7mvDODv",
				"id": "2U5WueTLIK5WJLD7mvDODv",
				"is_local": false,
				"name": "Wishing Well",
				"popularity": 84,
				"preview_url": null,
				"track_number": 15,
				"type": "track",
				"uri": "spotify:track:2U5WueTLIK5WJLD7mvDODv"
			},
			{
				"album": {
					"album_type": "album",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
							},
							"href": "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
							"id": "4MCBfE4596Uoi2O4DtmEMz",
							"name": "Juice WRLD",
							"type": "artist",
							"uri": "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AG",
						"AL",
						"AM",
						"AO",
						"AR",
						"AT",
						"AU",
						"AZ",
						"BA",
						"BB",
						"BD",
						"BE",
						"BG",
						"BH",
						"BI",
						"BJ",
						"BO",
						"BR",
						"BS",
						"BT",
						"BW",
						"BY",
						"BZ",
						"CA",
						"CD",
						"CG",
						"CH",
						"CI",
						"CL",
						"CM",
						"CO",
						"CR",
						"CV",
						"CW",
						"CY",
						"CZ",
						"DE",
						"DJ",
						"DK",
						"DM",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FJ",
						"FM",
						"FR",
						"GA",
						"GB",
						"GD",
						"GE",
						"GH",
						"GM",
						"GN",
						"GQ",
						"GR",
						"GT",
						"GW",
						"GY",
						"HK",
						"HN",
						"HR",
						"HT",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IQ",
						"IS",
						"IT",
						"JM",
						"JO",
						"JP",
						"KE",
						"KG",
						"KH",
						"KI",
						"KM",
						"KN",
						"KR",
						"KW",
						"KZ",
						"LA",
						"LB",
						"LC",
						"LI",
						"LK",
						"LR",
						"LS",
						"LT",
						"LU",
						"LV",
						"LY",
						"MA",
						"MC",
						"MD",
						"ME",
						"MG",
						"MH",
						"MK",
						"ML",
						"MN",
						"MO",
						"MR",
						"MT",
						"MU",
						"MV",
						"MW",
						"MX",
						"MY",
						"MZ",
						"NA",
						"NE",
						"NG",
						"NI",
						"NL",
						"NO",
						"NP",
						"NR",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PG",
						"PH",
						"PK",
						"PL",
						"PS",
						"PT",
						"PW",
						"PY",
						"QA",
						"RO",
						"RS",
						"RU",
						"RW",
						"SA",
						"SB",
						"SC",
						"SE",
						"SG",
						"SI",
						"SK",
						"SL",
						"SM",
						"SN",
						"SR",
						"ST",
						"SV",
						"SZ",
						"TD",
						"TG",
						"TH",
						"TJ",
						"TL",
						"TN",
						"TO",
						"TR",
						"TT",
						"TV",
						"TW",
						"TZ",
						"UA",
						"UG",
						"US",
						"UY",
						"UZ",
						"VC",
						"VE",
						"VN",
						"VU",
						"WS",
						"XK",
						"ZA",
						"ZM",
						"ZW"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/6tkjU4Umpo79wwkgPMV3nZ"
					},
					"href": "https://api.spotify.com/v1/albums/6tkjU4Umpo79wwkgPMV3nZ",
					"id": "6tkjU4Umpo79wwkgPMV3nZ",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273f7db43292a6a99b21b51d5b4",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02f7db43292a6a99b21b51d5b4",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851f7db43292a6a99b21b51d5b4",
							"width": 64
						}
					],
					"name": "Goodbye & Good Riddance",
					"release_date": "2018-12-10",
					"release_date_precision": "day",
					"total_tracks": 17,
					"type": "album",
					"uri": "spotify:album:6tkjU4Umpo79wwkgPMV3nZ"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
						},
						"href": "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
						"id": "4MCBfE4596Uoi2O4DtmEMz",
						"name": "Juice WRLD",
						"type": "artist",
						"uri": "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AG",
					"AL",
					"AM",
					"AO",
					"AR",
					"AT",
					"AU",
					"AZ",
					"BA",
					"BB",
					"BD",
					"BE",
					"BG",
					"BH",
					"BI",
					"BJ",
					"BO",
					"BR",
					"BS",
					"BT",
					"BW",
					"BY",
					"BZ",
					"CA",
					"CD",
					"CG",
					"CH",
					"CI",
					"CL",
					"CM",
					"CO",
					"CR",
					"CV",
					"CW",
					"CY",
					"CZ",
					"DE",
					"DJ",
					"DK",
					"DM",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FJ",
					"FM",
					"FR",
					"GA",
					"GB",
					"GD",
					"GE",
					"GH",
					"GM",
					"GN",
					"GQ",
					"GR",
					"GT",
					"GW",
					"GY",
					"HK",
					"HN",
					"HR",
					"HT",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IQ",
					"IS",
					"IT",
					"JM",
					"JO",
					"JP",
					"KE",
					"KG",
					"KH",
					"KI",
					"KM",
					"KN",
					"KR",
					"KW",
					"KZ",
					"LA",
					"LB",
					"LC",
					"LI",
					"LK",
					"LR",
					"LS",
					"LT",
					"LU",
					"LV",
					"LY",
					"MA",
					"MC",
					"MD",
					"ME",
					"MG",
					"MH",
					"MK",
					"ML",
					"MN",
					"MO",
					"MR",
					"MT",
					"MU",
					"MV",
					"MW",
					"MX",
					"MY",
					"MZ",
					"NA",
					"NE",
					"NG",
					"NI",
					"NL",
					"NO",
					"NP",
					"NR",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PG",
					"PH",
					"PK",
					"PL",
					"PS",
					"PT",
					"PW",
					"PY",
					"QA",
					"RO",
					"RS",
					"RU",
					"RW",
					"SA",
					"SB",
					"SC",
					"SE",
					"SG",
					"SI",
					"SK",
					"SL",
					"SM",
					"SN",
					"SR",
					"ST",
					"SV",
					"SZ",
					"TD",
					"TG",
					"TH",
					"TJ",
					"TL",
					"TN",
					"TO",
					"TR",
					"TT",
					"TV",
					"TW",
					"TZ",
					"UA",
					"UG",
					"US",
					"UY",
					"UZ",
					"VC",
					"VE",
					"VN",
					"VU",
					"WS",
					"XK",
					"ZA",
					"ZM",
					"ZW"
				],
				"disc_number": 1,
				"duration_ms": 239835,
				"explicit": true,
				"external_ids": {
					"isrc": "USUG11800685"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/285pBltuF7vW8TeWk8hdRR"
				},
				"href": "https://api.spotify.com/v1/tracks/285pBltuF7vW8TeWk8hdRR",
				"id": "285pBltuF7vW8TeWk8hdRR",
				"is_local": false,
				"name": "Lucid Dreams",
				"popularity": 87,
				"preview_url": null,
				"track_number": 3,
				"type": "track",
				"uri": "spotify:track:285pBltuF7vW8TeWk8hdRR"
			},
			{
				"album": {
					"album_type": "album",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
							},
							"href": "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
							"id": "4MCBfE4596Uoi2O4DtmEMz",
							"name": "Juice WRLD",
							"type": "artist",
							"uri": "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AG",
						"AL",
						"AM",
						"AO",
						"AR",
						"AT",
						"AU",
						"AZ",
						"BA",
						"BB",
						"BD",
						"BE",
						"BG",
						"BH",
						"BI",
						"BJ",
						"BO",
						"BR",
						"BS",
						"BT",
						"BW",
						"BY",
						"BZ",
						"CA",
						"CD",
						"CG",
						"CH",
						"CI",
						"CL",
						"CM",
						"CO",
						"CR",
						"CV",
						"CW",
						"CY",
						"CZ",
						"DE",
						"DJ",
						"DK",
						"DM",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FJ",
						"FM",
						"FR",
						"GA",
						"GB",
						"GD",
						"GE",
						"GH",
						"GM",
						"GN",
						"GQ",
						"GR",
						"GT",
						"GW",
						"GY",
						"HK",
						"HN",
						"HR",
						"HT",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IQ",
						"IS",
						"IT",
						"JM",
						"JO",
						"JP",
						"KE",
						"KG",
						"KH",
						"KI",
						"KM",
						"KN",
						"KR",
						"KW",
						"KZ",
						"LA",
						"LB",
						"LC",
						"LI",
						"LK",
						"LR",
						"LS",
						"LT",
						"LU",
						"LV",
						"LY",
						"MA",
						"MC",
						"MD",
						"ME",
						"MG",
						"MH",
						"MK",
						"ML",
						"MN",
						"MO",
						"MR",
						"MT",
						"MU",
						"MV",
						"MW",
						"MX",
						"MY",
						"MZ",
						"NA",
						"NE",
						"NG",
						"NI",
						"NL",
						"NO",
						"NP",
						"NR",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PG",
						"PH",
						"PK",
						"PL",
						"PS",
						"PT",
						"PW",
						"PY",
						"QA",
						"RO",
						"RS",
						"RU",
						"RW",
						"SA",
						"SB",
						"SC",
						"SE",
						"SG",
						"SI",
						"SK",
						"SL",
						"SM",
						"SN",
						"SR",
						"ST",
						"SV",
						"SZ",
						"TD",
						"TG",
						"TH",
						"TJ",
						"TL",
						"TN",
						"TO",
						"TR",
						"TT",
						"TV",
						"TW",
						"TZ",
						"UA",
						"UG",
						"US",
						"UY",
						"UZ",
						"VC",
						"VE",
						"VN",
						"VU",
						"WS",
						"XK",
						"ZA",
						"ZM",
						"ZW"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/6tkjU4Umpo79wwkgPMV3nZ"
					},
					"href": "https://api.spotify.com/v1/albums/6tkjU4Umpo79wwkgPMV3nZ",
					"id": "6tkjU4Umpo79wwkgPMV3nZ",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273f7db43292a6a99b21b51d5b4",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02f7db43292a6a99b21b51d5b4",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851f7db43292a6a99b21b51d5b4",
							"width": 64
						}
					],
					"name": "Goodbye & Good Riddance",
					"release_date": "2018-12-10",
					"release_date_precision": "day",
					"total_tracks": 17,
					"type": "album",
					"uri": "spotify:album:6tkjU4Umpo79wwkgPMV3nZ"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
						},
						"href": "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
						"id": "4MCBfE4596Uoi2O4DtmEMz",
						"name": "Juice WRLD",
						"type": "artist",
						"uri": "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AG",
					"AL",
					"AM",
					"AO",
					"AR",
					"AT",
					"AU",
					"AZ",
					"BA",
					"BB",
					"BD",
					"BE",
					"BG",
					"BH",
					"BI",
					"BJ",
					"BO",
					"BR",
					"BS",
					"BT",
					"BW",
					"BY",
					"BZ",
					"CA",
					"CD",
					"CG",
					"CH",
					"CI",
					"CL",
					"CM",
					"CO",
					"CR",
					"CV",
					"CW",
					"CY",
					"CZ",
					"DE",
					"DJ",
					"DK",
					"DM",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FJ",
					"FM",
					"FR",
					"GA",
					"GB",
					"GD",
					"GE",
					"GH",
					"GM",
					"GN",
					"GQ",
					"GR",
					"GT",
					"GW",
					"GY",
					"HK",
					"HN",
					"HR",
					"HT",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IQ",
					"IS",
					"IT",
					"JM",
					"JO",
					"JP",
					"KE",
					"KG",
					"KH",
					"KI",
					"KM",
					"KN",
					"KR",
					"KW",
					"KZ",
					"LA",
					"LB",
					"LC",
					"LI",
					"LK",
					"LR",
					"LS",
					"LT",
					"LU",
					"LV",
					"LY",
					"MA",
					"MC",
					"MD",
					"ME",
					"MG",
					"MH",
					"MK",
					"ML",
					"MN",
					"MO",
					"MR",
					"MT",
					"MU",
					"MV",
					"MW",
					"MX",
					"MY",
					"MZ",
					"NA",
					"NE",
					"NG",
					"NI",
					"NL",
					"NO",
					"NP",
					"NR",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PG",
					"PH",
					"PK",
					"PL",
					"PS",
					"PT",
					"PW",
					"PY",
					"QA",
					"RO",
					"RS",
					"RU",
					"RW",
					"SA",
					"SB",
					"SC",
					"SE",
					"SG",
					"SI",
					"SK",
					"SL",
					"SM",
					"SN",
					"SR",
					"ST",
					"SV",
					"SZ",
					"TD",
					"TG",
					"TH",
					"TJ",
					"TL",
					"TN",
					"TO",
					"TR",
					"TT",
					"TV",
					"TW",
					"TZ",
					"UA",
					"UG",
					"US",
					"UY",
					"UZ",
					"VC",
					"VE",
					"VN",
					"VU",
					"WS",
					"XK",
					"ZA",
					"ZM",
					"ZW"
				],
				"disc_number": 1,
				"duration_ms": 175755,
				"explicit": true,
				"external_ids": {
					"isrc": "USUG11800945"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/3oDkdAySo1VQQG0ptV7uwa"
				},
				"href": "https://api.spotify.com/v1/tracks/3oDkdAySo1VQQG0ptV7uwa",
				"id": "3oDkdAySo1VQQG0ptV7uwa",
				"is_local": false,
				"name": "Lean Wit Me",
				"popularity": 81,
				"preview_url": null,
				"track_number": 7,
				"type": "track",
				"uri": "spotify:track:3oDkdAySo1VQQG0ptV7uwa"
			},
			{
				"album": {
					"album_type": "album",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
							},
							"href": "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
							"id": "4MCBfE4596Uoi2O4DtmEMz",
							"name": "Juice WRLD",
							"type": "artist",
							"uri": "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AG",
						"AL",
						"AM",
						"AO",
						"AR",
						"AT",
						"AU",
						"AZ",
						"BA",
						"BB",
						"BD",
						"BE",
						"BF",
						"BG",
						"BH",
						"BI",
						"BJ",
						"BN",
						"BO",
						"BR",
						"BS",
						"BT",
						"BW",
						"BY",
						"BZ",
						"CA",
						"CD",
						"CG",
						"CH",
						"CI",
						"CL",
						"CM",
						"CO",
						"CR",
						"CV",
						"CW",
						"CY",
						"CZ",
						"DE",
						"DJ",
						"DK",
						"DM",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FJ",
						"FM",
						"FR",
						"GA",
						"GB",
						"GD",
						"GE",
						"GH",
						"GM",
						"GN",
						"GQ",
						"GR",
						"GT",
						"GW",
						"GY",
						"HK",
						"HN",
						"HR",
						"HT",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IQ",
						"IS",
						"IT",
						"JM",
						"JO",
						"JP",
						"KE",
						"KG",
						"KH",
						"KI",
						"KM",
						"KN",
						"KR",
						"KW",
						"KZ",
						"LA",
						"LB",
						"LC",
						"LI",
						"LK",
						"LR",
						"LS",
						"LT",
						"LU",
						"LV",
						"LY",
						"MA",
						"MC",
						"MD",
						"ME",
						"MG",
						"MH",
						"MK",
						"ML",
						"MN",
						"MO",
						"MR",
						"MT",
						"MU",
						"MV",
						"MW",
						"MX",
						"MY",
						"MZ",
						"NA",
						"NE",
						"NG",
						"NI",
						"NL",
						"NO",
						"NP",
						"NR",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PG",
						"PH",
						"PK",
						"PL",
						"PS",
						"PT",
						"PW",
						"PY",
						"QA",
						"RO",
						"RS",
						"RU",
						"RW",
						"SA",
						"SB",
						"SC",
						"SE",
						"SG",
						"SI",
						"SK",
						"SL",
						"SM",
						"SN",
						"SR",
						"ST",
						"SV",
						"SZ",
						"TD",
						"TG",
						"TH",
						"TJ",
						"TL",
						"TN",
						"TO",
						"TR",
						"TT",
						"TV",
						"TW",
						"TZ",
						"UA",
						"UG",
						"US",
						"UY",
						"UZ",
						"VC",
						"VE",
						"VN",
						"VU",
						"WS",
						"XK",
						"ZA",
						"ZM",
						"ZW"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/07tZDCAqxSIVEZywk0KDfT"
					},
					"href": "https://api.spotify.com/v1/albums/07tZDCAqxSIVEZywk0KDfT",
					"id": "07tZDCAqxSIVEZywk0KDfT",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273c820e86be3bcbc65e5b88ef0",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02c820e86be3bcbc65e5b88ef0",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851c820e86be3bcbc65e5b88ef0",
							"width": 64
						}
					],
					"name": "Fighting Demons",
					"release_date": "2021-12-10",
					"release_date_precision": "day",
					"total_tracks": 18,
					"type": "album",
					"uri": "spotify:album:07tZDCAqxSIVEZywk0KDfT"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
						},
						"href": "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
						"id": "4MCBfE4596Uoi2O4DtmEMz",
						"name": "Juice WRLD",
						"type": "artist",
						"uri": "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AG",
					"AL",
					"AM",
					"AO",
					"AR",
					"AT",
					"AU",
					"AZ",
					"BA",
					"BB",
					"BD",
					"BE",
					"BF",
					"BG",
					"BH",
					"BI",
					"BJ",
					"BN",
					"BO",
					"BR",
					"BS",
					"BT",
					"BW",
					"BY",
					"BZ",
					"CA",
					"CD",
					"CG",
					"CH",
					"CI",
					"CL",
					"CM",
					"CO",
					"CR",
					"CV",
					"CW",
					"CY",
					"CZ",
					"DE",
					"DJ",
					"DK",
					"DM",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FJ",
					"FM",
					"FR",
					"GA",
					"GB",
					"GD",
					"GE",
					"GH",
					"GM",
					"GN",
					"GQ",
					"GR",
					"GT",
					"GW",
					"GY",
					"HK",
					"HN",
					"HR",
					"HT",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IQ",
					"IS",
					"IT",
					"JM",
					"JO",
					"JP",
					"KE",
					"KG",
					"KH",
					"KI",
					"KM",
					"KN",
					"KR",
					"KW",
					"KZ",
					"LA",
					"LB",
					"LC",
					"LI",
					"LK",
					"LR",
					"LS",
					"LT",
					"LU",
					"LV",
					"LY",
					"MA",
					"MC",
					"MD",
					"ME",
					"MG",
					"MH",
					"MK",
					"ML",
					"MN",
					"MO",
					"MR",
					"MT",
					"MU",
					"MV",
					"MW",
					"MX",
					"MY",
					"MZ",
					"NA",
					"NE",
					"NG",
					"NI",
					"NL",
					"NO",
					"NP",
					"NR",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PG",
					"PH",
					"PK",
					"PL",
					"PS",
					"PT",
					"PW",
					"PY",
					"QA",
					"RO",
					"RS",
					"RU",
					"RW",
					"SA",
					"SB",
					"SC",
					"SE",
					"SG",
					"SI",
					"SK",
					"SL",
					"SM",
					"SN",
					"SR",
					"ST",
					"SV",
					"SZ",
					"TD",
					"TG",
					"TH",
					"TJ",
					"TL",
					"TN",
					"TO",
					"TR",
					"TT",
					"TV",
					"TW",
					"TZ",
					"UA",
					"UG",
					"US",
					"UY",
					"UZ",
					"VC",
					"VE",
					"VN",
					"VU",
					"WS",
					"XK",
					"ZA",
					"ZM",
					"ZW"
				],
				"disc_number": 1,
				"duration_ms": 231220,
				"explicit": true,
				"external_ids": {
					"isrc": "USUG12105423"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/2quVkyLSVr5wX2QIhnexUt"
				},
				"href": "https://api.spotify.com/v1/tracks/2quVkyLSVr5wX2QIhnexUt",
				"id": "2quVkyLSVr5wX2QIhnexUt",
				"is_local": false,
				"name": "Already Dead",
				"popularity": 85,
				"preview_url": null,
				"track_number": 2,
				"type": "track",
				"uri": "spotify:track:2quVkyLSVr5wX2QIhnexUt"
			},
			{
				"album": {
					"album_type": "album",
					"artists": [
						{
							"external_urls": {
								"spotify": "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of"
							},
							"href": "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
							"id": "0LyfQWJT6nXafLPZqxe9Of",
							"name": "Various Artists",
							"type": "artist",
							"uri": "spotify:artist:0LyfQWJT6nXafLPZqxe9Of"
						}
					],
					"available_markets": [
						"AD",
						"AE",
						"AG",
						"AL",
						"AM",
						"AO",
						"AR",
						"AT",
						"AU",
						"AZ",
						"BA",
						"BB",
						"BD",
						"BE",
						"BF",
						"BG",
						"BH",
						"BI",
						"BJ",
						"BN",
						"BO",
						"BR",
						"BS",
						"BT",
						"BW",
						"BY",
						"BZ",
						"CA",
						"CD",
						"CG",
						"CH",
						"CI",
						"CL",
						"CM",
						"CO",
						"CR",
						"CV",
						"CW",
						"CY",
						"CZ",
						"DE",
						"DJ",
						"DK",
						"DM",
						"DO",
						"DZ",
						"EC",
						"EE",
						"EG",
						"ES",
						"FI",
						"FJ",
						"FM",
						"FR",
						"GA",
						"GB",
						"GD",
						"GE",
						"GH",
						"GM",
						"GN",
						"GQ",
						"GR",
						"GT",
						"GW",
						"GY",
						"HK",
						"HN",
						"HR",
						"HT",
						"HU",
						"ID",
						"IE",
						"IL",
						"IN",
						"IQ",
						"IS",
						"IT",
						"JM",
						"JO",
						"JP",
						"KE",
						"KG",
						"KH",
						"KI",
						"KM",
						"KN",
						"KR",
						"KW",
						"KZ",
						"LA",
						"LB",
						"LC",
						"LI",
						"LK",
						"LR",
						"LS",
						"LT",
						"LU",
						"LV",
						"LY",
						"MA",
						"MC",
						"MD",
						"ME",
						"MG",
						"MH",
						"MK",
						"ML",
						"MN",
						"MO",
						"MR",
						"MT",
						"MU",
						"MV",
						"MW",
						"MX",
						"MY",
						"MZ",
						"NA",
						"NE",
						"NG",
						"NI",
						"NL",
						"NO",
						"NP",
						"NR",
						"NZ",
						"OM",
						"PA",
						"PE",
						"PG",
						"PH",
						"PK",
						"PL",
						"PS",
						"PT",
						"PW",
						"PY",
						"QA",
						"RO",
						"RS",
						"RU",
						"RW",
						"SA",
						"SB",
						"SC",
						"SE",
						"SG",
						"SI",
						"SK",
						"SL",
						"SM",
						"SN",
						"SR",
						"ST",
						"SV",
						"SZ",
						"TD",
						"TG",
						"TH",
						"TJ",
						"TL",
						"TN",
						"TO",
						"TR",
						"TT",
						"TV",
						"TW",
						"TZ",
						"UA",
						"UG",
						"US",
						"UY",
						"UZ",
						"VC",
						"VE",
						"VN",
						"VU",
						"WS",
						"XK",
						"ZA",
						"ZM",
						"ZW"
					],
					"external_urls": {
						"spotify": "https://open.spotify.com/album/35s58BRTGAEWztPo9WqCIs"
					},
					"href": "https://api.spotify.com/v1/albums/35s58BRTGAEWztPo9WqCIs",
					"id": "35s58BRTGAEWztPo9WqCIs",
					"images": [
						{
							"height": 640,
							"url": "https://i.scdn.co/image/ab67616d0000b273e2e352d89826aef6dbd5ff8f",
							"width": 640
						},
						{
							"height": 300,
							"url": "https://i.scdn.co/image/ab67616d00001e02e2e352d89826aef6dbd5ff8f",
							"width": 300
						},
						{
							"height": 64,
							"url": "https://i.scdn.co/image/ab67616d00004851e2e352d89826aef6dbd5ff8f",
							"width": 64
						}
					],
					"name": "Spider-Man: Into the Spider-Verse (Soundtrack From & Inspired by the Motion Picture)",
					"release_date": "2018-12-14",
					"release_date_precision": "day",
					"total_tracks": 13,
					"type": "album",
					"uri": "spotify:album:35s58BRTGAEWztPo9WqCIs"
				},
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
						},
						"href": "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
						"id": "4MCBfE4596Uoi2O4DtmEMz",
						"name": "Juice WRLD",
						"type": "artist",
						"uri": "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
					},
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/1jIVEaq8GmqMYb8nFNAZgb"
						},
						"href": "https://api.spotify.com/v1/artists/1jIVEaq8GmqMYb8nFNAZgb",
						"id": "1jIVEaq8GmqMYb8nFNAZgb",
						"name": "Seezyn",
						"type": "artist",
						"uri": "spotify:artist:1jIVEaq8GmqMYb8nFNAZgb"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AG",
					"AL",
					"AM",
					"AO",
					"AR",
					"AT",
					"AU",
					"AZ",
					"BA",
					"BB",
					"BD",
					"BE",
					"BF",
					"BG",
					"BH",
					"BI",
					"BJ",
					"BN",
					"BO",
					"BR",
					"BS",
					"BT",
					"BW",
					"BY",
					"BZ",
					"CA",
					"CD",
					"CG",
					"CH",
					"CI",
					"CL",
					"CM",
					"CO",
					"CR",
					"CV",
					"CW",
					"CY",
					"CZ",
					"DE",
					"DJ",
					"DK",
					"DM",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FJ",
					"FM",
					"FR",
					"GA",
					"GB",
					"GD",
					"GE",
					"GH",
					"GM",
					"GN",
					"GQ",
					"GR",
					"GT",
					"GW",
					"GY",
					"HK",
					"HN",
					"HR",
					"HT",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IQ",
					"IS",
					"IT",
					"JM",
					"JO",
					"JP",
					"KE",
					"KG",
					"KH",
					"KI",
					"KM",
					"KN",
					"KR",
					"KW",
					"KZ",
					"LA",
					"LB",
					"LC",
					"LI",
					"LK",
					"LR",
					"LS",
					"LT",
					"LU",
					"LV",
					"LY",
					"MA",
					"MC",
					"MD",
					"ME",
					"MG",
					"MH",
					"MK",
					"ML",
					"MN",
					"MO",
					"MR",
					"MT",
					"MU",
					"MV",
					"MW",
					"MX",
					"MY",
					"MZ",
					"NA",
					"NE",
					"NG",
					"NI",
					"NL",
					"NO",
					"NP",
					"NR",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PG",
					"PH",
					"PK",
					"PL",
					"PS",
					"PT",
					"PW",
					"PY",
					"QA",
					"RO",
					"RS",
					"RU",
					"RW",
					"SA",
					"SB",
					"SC",
					"SE",
					"SG",
					"SI",
					"SK",
					"SL",
					"SM",
					"SN",
					"SR",
					"ST",
					"SV",
					"SZ",
					"TD",
					"TG",
					"TH",
					"TJ",
					"TL",
					"TN",
					"TO",
					"TR",
					"TT",
					"TV",
					"TW",
					"TZ",
					"UA",
					"UG",
					"US",
					"UY",
					"UZ",
					"VC",
					"VE",
					"VN",
					"VU",
					"WS",
					"XK",
					"ZA",
					"ZM",
					"ZW"
				],
				"disc_number": 1,
				"duration_ms": 205800,
				"explicit": false,
				"external_ids": {
					"isrc": "USUG11802778"
				},
				"external_urls": {
					"spotify": "https://open.spotify.com/track/6rz0dTA0PdhXImFV5EjM0w"
				},
				"href": "https://api.spotify.com/v1/tracks/6rz0dTA0PdhXImFV5EjM0w",
				"id": "6rz0dTA0PdhXImFV5EjM0w",
				"is_local": false,
				"name": "Hide (feat. Seezyn)",
				"popularity": 79,
				"preview_url": null,
				"track_number": 7,
				"type": "track",
				"uri": "spotify:track:6rz0dTA0PdhXImFV5EjM0w"
			}
		],
		"limit": 7,
		"next": "https://api.spotify.com/v1/search?query=juice+wrld&type=track&offset=7&limit=7",
		"offset": 0,
		"previous": null,
		"total": 1436
	}
}